vout: starfive: correct MODULE_DEVICE_TABLE for pin driver
Avoid an error

    In file included from drivers/gpu/drm/i2c/tda998x_pin.c:1:
    drivers/gpu/drm/i2c/tda998x_pin.c:27:25: error:
    ‘starfive_drm_dt_ids’ undeclared here (not in a function)
       27 | MODULE_DEVICE_TABLE(of, starfive_drm_dt_ids);
          |                         ^~~~~~~~~~~~~~~~~~~

Fixes: 4bb9a5d4dd95 ("vout: starfive: Add driver for the StarFive JH7110 display subsystem")
Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>